version: '3.7'

services:
  api-gateway:
    container_name: school-api-gateway
    build:
      context: .
      target: development
      dockerfile: dockerfile
    volumes:
      - .:/usr/src/school-api-gateway
    ports:
      - 3333:3333
    command: yarn start:dev
    env_file: .env
    networks:
      - api

networks:
  api:
